map $http_upgrade $connection_upgrade {
    default upgrade;
    '' close;
}

server {
    listen 80; #Nginx listens for requests coming to port 80
    server_name _; #Accept requests for any domain name

    location /api/ {
        client_max_body_size 60m;
        proxy_http_version 1.1;
        proxy_set_header Host $host; #Sends the original website name (host) to the backend.
        proxy_set_header X-Real-IP $remote_addr; #Sends the real IP address of the user.
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; #Keeps a list of all proxy servers the request passed through.
        proxy_set_header X-Forwarded-Proto $scheme; #Tells the backend whether the original request used HTTP or HTTPS.
        proxy_set_header X-Forwarded-Host $host; #Sends the original host/domain name.
        proxy_set_header Upgrade $http_upgrade; #Passes upgrade requests (like WebSockets) to the backend.
        proxy_set_header Connection $connection_upgrade; #Tells the backend whether to upgrade the connection or close it.
        proxy_read_timeout 300s; #Waits up to 5 minutes for the backend to send a response.
        proxy_send_timeout 300s; #Waits up to 5 minutes for the backend to receive the request.
        proxy_pass http://backend:8000/; #Forwards the request to your FastAPI application running on the backend container.
    }

    location / {
        proxy_http_version 1.1;
        proxy_set_header Host $host; #Sends the original host name to the frontend.
        proxy_set_header X-Real-IP $remote_addr; #Sends the user's real IP address.
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; #Forwards the user's IP information through proxies.
        proxy_set_header X-Forwarded-Proto $scheme; #Tells the frontend whether the request was HTTP or HTTPS.
        proxy_set_header X-Forwarded-Host $host; #Sends the original host/domain name. 
        proxy_set_header Upgrade $http_upgrade; #Passes upgrade requests (like WebSockets) to the frontend.
        proxy_set_header Connection $connection_upgrade; #Tells the frontend whether to upgrade the connection or close it.
        proxy_read_timeout 300s; #Waits up to 5 minutes for the frontend to send a response.
        proxy_send_timeout 300s; #Waits up to 5 minutes while sending data to the frontend.
        proxy_pass http://frontend:4173; #Forwards the request to the frontend container running on port 4173.
    }
}